Jia dev: added Courses Recycler View!
jiangzhengwenjz/upeers pull request #5
Opened 2019-11-06 17:02 UTC by facade1801

2019-11-07 02:29 UTC, jiangzhengwenjz requested changes
Please fix all the mentioned stuff. Keep the consistency of code style is important to projects being worked on by multiple people.

2019-11-07 02:29 UTC, jiangzhengwenjz commented on app/src/main/java/com/example/upeers/ui/home/CourseInfoAdapter.kt
> +}
According to POSIX, text files should end with newline, otherwise github will place such a marker here to warn you. (Please check other files)

2019-11-07 02:29 UTC, jiangzhengwenjz commented on app/src/main/java/com/example/upeers/ui/home/CourseInfoAdapter.kt
> +//) {}
Do you think we should remove this class?

2019-11-07 02:29 UTC, jiangzhengwenjz commented on app/src/main/java/com/example/upeers/ui/home/CourseInfoAdapter.kt
> +//        holder.avatar.setImageResource(myDataSet[position].avatar)    }
Let's agree that comments should start from the current indent level.

2019-11-07 02:29 UTC, jiangzhengwenjz commented on app/src/main/java/com/example/upeers/message/MessageInfoFragment.kt
>  //        mPlusOneButton = view.findViewById<View>(R.id.plus_one_button) as PlusOneButton
Let's agree that comments should start from the current indent level.

2019-11-08 07:59 UTC, facade1801 commented
> Please fix all the mentioned stuff. Keep the consistency of code style is important to projects being worked on by multiple people.

Please check and agree with merging if there's no problem. Thanks.
BTW It says "Merging can be performed automatically once the requested changes are addressed", but I addressed the changes, and it didn't happen. Wonder why.

2019-11-08 15:31 UTC, jiangzhengwenjz commented
This PR still has some problems (some of the requested changes are not addressed) but I will handle it this afternoon for your convenience.

2019-11-09 05:45 UTC, merged